# jekyll theme
#theme: jekyll-theme-cayman
remote_theme: andrewbanchich/forty-jekyll-theme

# site settings
title: Tejasvi Khurana
description: Social Media Manager
email: tejasvi16@gmail.com

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6
