# jekyll theme
#theme: jekyll-theme-cayman
remote_theme: andrewbanchich/forty-jekyll-theme

# site settings
title: Tejasvi
subtitle: Khurana
description: A Digital Marketing enthusiast. Social Media Manager by profession. Aspiring to dive into Client Servicing.
email: tejasvi16@gmail.com

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6
