# jekyll theme
#theme: jekyll-theme-cayman
remote_theme: andrewbanchich/forty-jekyll-theme

# site settings

baseurl: # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
title: Tejasvi
subtitle: Khurana
description: A Digital Marketing enthusiast.<br>Social Media Manager by profession.<br>Aspiring to dive into Client Servicing.
email: tejasvi16@gmail.com
author: xxx xxx
street_address: xxx xxx xxx
city: Noida
state: UP
zip_code: 201301
country: India
phone: (+91) xxxxxxxxxx
collections:
  campaigns:
    output: true

# homepage tiles
tiles_source: pages # accepts "posts" or "pages"
tiles_count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/tejasvi-khurana-21849553/
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
